// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Study.HotChocolate.Data;

#nullable disable

namespace Study.Hotchocolate.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Study.HotChocolate.Data.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Study.HotChocolate.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Study.HotChocolate.Data.User.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AdCode")
                                .HasMaxLength(255);

                            b1.Property<string>("Detail")
                                .HasMaxLength(255);

                            b1
                                .ToJson("Address")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Study.HotChocolate.Data.Post", b =>
                {
                    b.HasOne("Study.HotChocolate.Data.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Study.HotChocolate.Data.User", b =>
                {
                    b.OwnsMany("Study.HotChocolate.Data.Identity", "Identities", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.HasKey("UserId", "__synthesizedOrdinal");

                            b1.ToTable("User");

                            b1
                                .ToJson("Identities")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Study.HotChocolate.Data.State", "State", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Remark")
                                .HasMaxLength(255);

                            b1.Property<bool>("Value");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1
                                .ToJson("State")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Identities");

                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("Study.HotChocolate.Data.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
